---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/cfops
inputs:
  - name: environment-lock
  - name: london-meta
  - name: cfops
    path: src/github.com/pivotalservices/cfops
params:
  IAAS:
run:
  path: src/github.com/pivotalservices/cfops/ci/scripts/system
